### ISSUE TITLE
Chọn đề tài

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#11]
thầy đã đưa cho danh sách đề tài. anh em có ý tưởng gì hoặc ý kiến muốn chọn đề tài nào của thầy thì comment.

**Comment by sonpham2k** [comment]
t thấy làm AR khá ok, nhìn hay

**Comment by Nam0606** [comment]
đề tài mình vẽ 2d từ file dxf hả Nguyên

**Comment by sonpham2k** [comment]
cái vẽ 2d, dùng AutoCad hả, tải về nặng lắm, có nên chọn k?

**Comment by Nam0606** [comment]
anh em đã học python chưa đấy

**Comment by sonpham2k** [comment]
vào codelearn học chắc sẽ biết chút ít

**Comment by jake1512** [comment]
ok thế chốt cái đề tài 29 nhể
