### ISSUE TITLE
practice

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#13]
Tập vẽ hình 2D, tìm hiểu cấu trúc file dxf và thư viện ezdxf

**Comment by Nam0606** [comment]
có cần tìm hiểu về 3d ko???

**Comment by jake1512** [comment]
2D thôi đã

**Comment by jake1512** [comment]
![image](https://user-images.githubusercontent.com/25949891/103484290-36307f00-4e20-11eb-9d5c-cfe48282d7d9.png)
vẽ theo hình này
