### ISSUE TITLE
Xử lý file xml

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#16]
anh Hoàng đưa một file data.xml, t với m tìm cách extract các thứ dữ liệu từ nó rồi đưa vào trong file vẽ

**Comment by jake1512** [comment]
@quangtran314 m xem thử có cái thư viện py nào đọc đc cái file xml rồi gửi t xem

**Comment by quangtran314** [comment]
cái này tra thấy trên mạng xài cái này đc này https://docs.python.org/3/library/xml.etree.elementtree.html
xem qua phát

**Comment by jake1512** [comment]
ok để t xem qua rồi đẩy lên cho
