### ISSUE TITLE
Xử lý dimension 

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#17]
@sonpham2k @Nam0606 anh em xem cách xử lý các cái dimension dựa vào các hình

**Comment by sonpham2k** [comment]
t làm xong r ô

**Comment by sonpham2k** [comment]
t tạm thời ok r nhé, nhưng nó chỉ là tương tự, không giống hoàn toàn với hình mẫu, cho t thêm thời gian để đọc thư viện ezdxf

**Comment by sonpham2k** [comment]
t hoàn thiện rồi nhé, đã đúng như yêu cầu

**Comment by Nam0606** [comment]
ok rồi nhá
