### ISSUE TITLE
Vẽ hình 3D

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#18]
t thấy trong cái data.xml có các cái W, D, H các thứ nên m thử xem ntn

**Comment by jake1512** [comment]
RX, RY, RZ là rotate? theo các trụ X Y Z?

**Comment by quangtran314** [comment]
Thấy trong sheet hỏi anh Hoàng có nhắc đến mấy cái RX, RY, RZ nên chắc là có phải xoay đấy.
Mà chưa biết xoay như nào. Hỏi lại anh đi.

**Comment by jake1512** [comment]
https://khanacademy.org/computing/computer-programming/programming-games-visualizations/programming-3d-shapes/a/rotating-3d-shapes?fbclid=IwAR1PcsQ0HcssRzCu_a-blw2yM_rVEFsArIz2pJhG6NxJnAwQxzREDhv_pHY

tham khảo link này anh vừa gửi

**Comment by quangtran314** [comment]
Ok, để tham khảo.

**Comment by quangtran314** [comment]
Xoay được rồi. T chuyển tọa độ sau khi xoay trong cái file rotation.py đấy.
