### ISSUE TITLE
Thay đổi cách vẽ

### ISSUE THREAD

**Issue by sonpham2k** [jake1512/SE04-Nhom29.1#19]

**Comment by quangtran314** [comment]
Thay đổi cái gì đây?

**Comment by jake1512** [comment]
thay đổi gì đây ông

**Comment by sonpham2k** [comment]
A Hoàng bảo chỉ cần vẽ 2D là được rồi ae

**Comment by sonpham2k** [comment]
không cần vẽ 3D đâu, ae tập trung lại vẽ 2D nhé

**Comment by jake1512** [comment]
hmm kay. lần sau nhớ comment thẳng vào lúc tạo issue ông ơi
