### ISSUE TITLE
vẽ bản vẽ kĩ thuật 2D

### ISSUE THREAD

**Issue by jake1512** [jake1512/SE04-Nhom29.1#20]
vẽ các hình vẽ kĩ thuật 2D tịnh tiến theo trục tọa độ

**Comment by Nam0606** [comment]
tịnh tiến theo trục nào v ae

**Comment by sonpham2k** [comment]
hình 2D gồm những j vậy?

**Comment by jake1512** [comment]
> hình 2D gồm những j vậy?


hình 2D gồm các part trong file xml mình được cho đấy hoặc như cái hình anh Nguyên gửi đấy

**Comment by jake1512** [comment]
> tịnh tiến theo trục nào v ae

t nghĩ là tịnh tiến theo trục X thôi cho thuận mắt

**Comment by quangtran314** [comment]
Tức là vẽ các tấm giống hình mẫu của anh Nguyên theo trục x chứ gì?

**Comment by jake1512** [comment]
> Tức là vẽ các tấm giống hình mẫu của anh Nguyên theo trục x chứ gì?

ờ chính nó

**Comment by jake1512** [comment]
đầy đủ các dimension với tên hình đặt ở dưới

**Comment by quangtran314** [comment]
ok, hiểu.

**Comment by jake1512** [comment]
aight
